### ISSUE TITLE
Verbose mode isn't verbose

### ISSUE THREAD

**Issue by varac** [afewmail/afew#181] opened 2018-02-20 21:08 UTC
```
  -v, --verbose         be more verbose, can be given multiple times
```

I tried giving `-v` multiple times in order to get *any* verbosity, but it just don't change anything.

```
» afew -t lastmod:3480603..3480605 
» afew -vvvvvv -t lastmod:3480603..3480605
» 
```

were messages tagged or not ?

**Comment by GuillaumeSeren** [comment] 2018-03-11 19:00
Hey @varac 
To me this is working fine on master see #180, so please test against master and reopen if issue is still there.

**Comment by varac** [comment] 2018-03-12 09:10
Still not giving any output at all to me, running latest master. 

```
⏻  ~  » afew -vvvvvvvv -t --new
⏻  ~  »
```

Can anybody else please try to reproduce ? I cannot reopen this issue.

**Comment by GuillaumeSeren** [comment] 2018-03-12 09:47
Hey @varac please test the issue against the 1.3.0 ?

**Comment by flokli** [comment] 2018-04-16 18:13
@varac I still can't reproduce logs verbose mode not being verbose, sorry.
Note having 2 `-v` parameters is already enough for loglevel `DEBUG` ;-)

The posted traceback is helpful.
`search_messages()` from `notmuch.query` raised a `XapianError`, most likely due to a wrongly formatted query string.
You might want to add some more debug log statements inside `afew/main.py`, to get an idea where it's crashing, while checking your afew configuration for invalid queries.

**Comment by flokli** [comment] 2018-04-19 10:44
Not sure about the setup, but I'd suspect some old/broken versions lingering around somewhere and being loaded. As we can't reproduce, I'd close this one.

**Closed by flokli** 2018-04-19 10:44 UTC
Labels: use-case, waiting-reply

**Comment by varac** [comment] 2018-07-05 19:18
@floki, the bug is triggered when using python2 instead of python3, see https://github.com/afewmail/afew/issues/180#issuecomment-402825613.
