### ISSUE TITLE
no error message no tags changed

### ISSUE THREAD

**Issue by bderembl** [afewmail/afew#165] opened 2017-10-24 17:41 UTC
with python 3.6, I run
`afew --tag --new -vv`
that doesn't do anything.
it seems that `options.enable_filters` is empty in main.py so that the script exits without doing anything and with no error message

**Comment by flokli** [comment] 2017-10-29 18:17
This looks weird. I also run python3.6, and it works for me.

Did it work before on another Python version? How does your config look like?

**Comment by GuillaumeSeren** [comment] 2017-10-30 14:14
Hey,
I just tested as well, on all python version I got and I confirm this is working on "2.7 3.4 3.6".

Maybe it comes from your config could share it ?

**Comment by bderembl** [comment] 2017-10-30 15:04
I just have the default config. I wonder why `options.enable_filters` is empty?

**Comment by flokli** [comment] 2017-10-30 16:01
Most likely something went wrong while parsing the config file, although I wasn't able to reproduce this with the default config.

**Comment by flokli** [comment] 2017-11-01 17:22
closing this for now.

**Closed by flokli** 2017-11-01 17:22 UTC
